version: "3.8"

services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env

  frontend:
    container_name: evolution_frontend
    image: evoapicloud/evolution-manager:homolog
    restart: always
    ports:
      - "3333:80"
    networks:
      - evolution-net

  redis:
    container_name: evolution_redis
    image: redis:7
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      evolution-net:
        aliases:
          - evolution-redis

  evolution-postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net
    expose:
      - "5432"

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge

# services:
#   evolution-api:
#     image: evoapicloud/evolution-api:v2.3.7
#     container_name: evolution_api
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#       - redis
#     volumes:
#       - evolution_instances:/evolution/instances

#   postgres:
#     image: postgres:15
#     container_name: evolution_postgres
#     restart: always
#     environment:
#       POSTGRES_DB: evolution_db
#       POSTGRES_USER: evolution_user
#       POSTGRES_PASSWORD: evolution_pass
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:7
#     container_name: evolution_redis
#     restart: always
#     volumes:
#       - redis_data:/data

# volumes:
#   evolution_instances:
#   postgres_data:
#   redis_data:
